Fri, 03 Jan 2020 07:08:59 - INFO - Connect to DB
Fri, 03 Jan 2020 07:08:59 - INFO - TRIZMA DB import
Fri, 03 Jan 2020 07:09:00 - INFO - 123TV DB import
Fri, 03 Jan 2020 07:15:11 - INFO - Connect to DB
Fri, 03 Jan 2020 07:15:11 - INFO - TRIZMA DB import
Fri, 03 Jan 2020 07:15:11 - INFO - 123TV DB import
Fri, 03 Jan 2020 07:17:07 - INFO - Connect to DB
Fri, 03 Jan 2020 07:17:07 - INFO - TRIZMA DB import
Fri, 03 Jan 2020 07:17:07 - INFO - Failed on TRIZMA DB import at: 2020-01-02_18-53-56, for following calling party: 4915732147392, for agent id: trz_bmaksimovic, with error:(pyodbc.DataError) ('22001', '[22001] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]String or binary data would be truncated. (8152) (SQLExecDirectW)')
[SQL: insert into records values('CC2Servicenummer','Belgrad','Nicht übermittelt','trz_bmaksimovic',                                  '4915732147392','','Nicht übermittelt','4915732147392_Saturday, December 28, 2019_12:49:59 PM')]
(Background on this error at: http://sqlalche.me/e/9h9h)
Fri, 03 Jan 2020 07:17:07 - INFO - 123TV DB import
Fri, 03 Jan 2020 07:18:13 - INFO - Connect to DB
Fri, 03 Jan 2020 07:18:13 - INFO - TRIZMA DB import
Fri, 03 Jan 2020 07:18:13 - INFO - Failed on TRIZMA DB import at: 2020-01-02_18-53-56, for following calling party: 492652989150, for agent id: trz_bmaksimovic, with error:(pyodbc.DataError) ('22001', '[22001] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]String or binary data would be truncated. (8152) (SQLExecDirectW)')
[SQL: insert into records values('CC2Servicenummer','Belgrad','Nicht übermittelt','trz_bmaksimovic',                                  '492652989150','','Nicht übermittelt','492652989150_Saturday, December 28, 2019_2:28:04 PM')]
(Background on this error at: http://sqlalche.me/e/9h9h)
Fri, 03 Jan 2020 07:18:13 - INFO - 123TV DB import
Fri, 03 Jan 2020 07:19:06 - INFO - Connect to DB
Fri, 03 Jan 2020 07:19:06 - ERROR - Exception on /records [GET]
Traceback (most recent call last):
  File "/home/python_project/hello.py", line 80, in get
    int(agent),
ValueError: invalid literal for int() with base 10: ''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.6/dist-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/python_project/hello.py", line 90, in get
    + str(e))
UnboundLocalError: local variable 'agentUsername' referenced before assignment
Fri, 03 Jan 2020 07:19:57 - INFO - Connect to DB
Fri, 03 Jan 2020 07:19:57 - INFO - TRIZMA DB import
Fri, 03 Jan 2020 07:19:57 - INFO - 123TV DB import
Fri, 03 Jan 2020 07:20:03 - INFO - Connect to DB
Fri, 03 Jan 2020 07:20:03 - INFO - TRIZMA DB import
Fri, 03 Jan 2020 07:20:03 - INFO - 123TV DB import
Fri, 03 Jan 2020 07:20:10 - INFO - Connect to DB
Fri, 03 Jan 2020 07:20:11 - INFO - TRIZMA DB import
Fri, 03 Jan 2020 07:20:11 - INFO - Failed on TRIZMA DB import at: 2020-01-02_18-53-56, for following calling party: 4933915990965, for agent id: trz_bmaksimovic, with error:(pyodbc.DataError) ('22001', '[22001] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]String or binary data would be truncated. (8152) (SQLExecDirectW)')
[SQL: insert into records values('CC2Servicenummer','Belgrad','Nicht übermittelt','trz_bmaksimovic',                                  '4933915990965','','Nicht übermittelt','4933915990965_Saturday, December 28, 2019_4:35:30 PM')]
(Background on this error at: http://sqlalche.me/e/9h9h)
Fri, 03 Jan 2020 07:20:11 - INFO - 123TV DB import
Fri, 03 Jan 2020 07:20:31 - INFO - Connect to DB
Fri, 03 Jan 2020 07:20:31 - INFO - TRIZMA DB import
Fri, 03 Jan 2020 07:20:31 - INFO - 123TV DB import
Fri, 03 Jan 2020 07:20:57 - INFO - Connect to DB
Fri, 03 Jan 2020 07:20:57 - INFO - TRIZMA DB import
Fri, 03 Jan 2020 07:20:57 - INFO - Failed on TRIZMA DB import at: 2020-01-02_18-53-56, for following calling party: 497121580124, for agent id: trz_bmaksimovic, with error:(pyodbc.DataError) ('22001', '[22001] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]String or binary data would be truncated. (8152) (SQLExecDirectW)')
[SQL: insert into records values('CC2Servicenummer','Belgrad','Nicht übermittelt','trz_bmaksimovic',                                  '497121580124','','Nicht übermittelt','497121580124_Saturday, December 28, 2019_5:30:56 PM')]
(Background on this error at: http://sqlalche.me/e/9h9h)
Fri, 03 Jan 2020 07:20:57 - INFO - 123TV DB import
Fri, 03 Jan 2020 07:21:30 - INFO - Connect to DB
Fri, 03 Jan 2020 07:21:30 - INFO - TRIZMA DB import
Fri, 03 Jan 2020 07:21:30 - INFO - 123TV DB import
Fri, 03 Jan 2020 07:21:36 - INFO - Connect to DB
Fri, 03 Jan 2020 07:21:36 - INFO - TRIZMA DB import
Fri, 03 Jan 2020 07:21:36 - INFO - 123TV DB import
Fri, 03 Jan 2020 07:22:15 - INFO - Connect to DB
Fri, 03 Jan 2020 07:22:15 - INFO - TRIZMA DB import
Fri, 03 Jan 2020 07:22:15 - INFO - 123TV DB import
Fri, 03 Jan 2020 07:22:36 - INFO - Connect to DB
Fri, 03 Jan 2020 07:22:36 - INFO - TRIZMA DB import
Fri, 03 Jan 2020 07:22:36 - INFO - 123TV DB import
Fri, 03 Jan 2020 07:22:42 - INFO - Connect to DB
Fri, 03 Jan 2020 07:22:42 - INFO - TRIZMA DB import
Fri, 03 Jan 2020 07:22:42 - INFO - Failed on TRIZMA DB import at: 2020-01-02_18-53-56, for following calling party: 491731864217, for agent id: trz_sstankovic, with error:(pyodbc.DataError) ('22001', '[22001] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]String or binary data would be truncated. (8152) (SQLExecDirectW)')
[SQL: insert into records values('CC2Servicenummer','Belgrad','Nicht übermittelt','trz_sstankovic',                                  '491731864217','','Nicht übermittelt','491731864217_Tuesday, December 31, 2019_12:52:51 PM')]
(Background on this error at: http://sqlalche.me/e/9h9h)
Fri, 03 Jan 2020 07:22:42 - INFO - 123TV DB import
Fri, 03 Jan 2020 07:23:08 - INFO - Connect to DB
Fri, 03 Jan 2020 07:23:08 - INFO - TRIZMA DB import
Fri, 03 Jan 2020 07:23:08 - INFO - 123TV DB import
Fri, 03 Jan 2020 07:23:20 - INFO - Connect to DB
Fri, 03 Jan 2020 07:23:20 - INFO - TRIZMA DB import
Fri, 03 Jan 2020 07:23:20 - INFO - 123TV DB import
Fri, 03 Jan 2020 07:23:26 - INFO - Connect to DB
Fri, 03 Jan 2020 07:23:26 - INFO - TRIZMA DB import
Fri, 03 Jan 2020 07:23:26 - INFO - Failed on TRIZMA DB import at: 2020-01-02_18-53-56, for following calling party: 4917655909929, for agent id: trz_sstankovic, with error:(pyodbc.DataError) ('22001', '[22001] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]String or binary data would be truncated. (8152) (SQLExecDirectW)')
[SQL: insert into records values('CC2Servicenummer','Belgrad','Nicht übermittelt','trz_sstankovic',                                  '4917655909929','','Nicht übermittelt','4917655909929_Tuesday, December 31, 2019_2:25:59 PM')]
(Background on this error at: http://sqlalche.me/e/9h9h)
Fri, 03 Jan 2020 07:23:26 - INFO - 123TV DB import
Fri, 03 Jan 2020 07:24:09 - INFO - Connect to DB
Fri, 03 Jan 2020 07:24:09 - INFO - TRIZMA DB import
Fri, 03 Jan 2020 07:24:09 - INFO - 123TV DB import
Fri, 03 Jan 2020 07:24:27 - INFO - Connect to DB
Fri, 03 Jan 2020 07:24:27 - INFO - TRIZMA DB import
Fri, 03 Jan 2020 07:24:27 - INFO - 123TV DB import
Fri, 03 Jan 2020 07:25:07 - INFO - Connect to DB
Fri, 03 Jan 2020 07:25:07 - INFO - TRIZMA DB import
Fri, 03 Jan 2020 07:25:07 - INFO - 123TV DB import
Fri, 03 Jan 2020 07:25:13 - INFO - Connect to DB
Fri, 03 Jan 2020 07:25:13 - INFO - TRIZMA DB import
Fri, 03 Jan 2020 07:25:13 - INFO - 123TV DB import
Fri, 03 Jan 2020 07:25:43 - INFO - Connect to DB
Fri, 03 Jan 2020 07:25:43 - INFO - TRIZMA DB import
Fri, 03 Jan 2020 07:25:43 - INFO - 123TV DB import
Fri, 03 Jan 2020 07:26:30 - INFO - Connect to DB
Fri, 03 Jan 2020 07:26:30 - INFO - TRIZMA DB import
Fri, 03 Jan 2020 07:26:30 - INFO - 123TV DB import
Fri, 03 Jan 2020 07:27:03 - INFO - Connect to DB
Fri, 03 Jan 2020 07:27:03 - INFO - TRIZMA DB import
Fri, 03 Jan 2020 07:27:03 - INFO - 123TV DB import
Fri, 03 Jan 2020 07:27:41 - INFO - Connect to DB
Fri, 03 Jan 2020 07:27:41 - INFO - TRIZMA DB import
Fri, 03 Jan 2020 07:27:41 - INFO - 123TV DB import
Fri, 03 Jan 2020 07:27:46 - INFO - Connect to DB
Fri, 03 Jan 2020 07:27:46 - INFO - TRIZMA DB import
Fri, 03 Jan 2020 07:27:46 - INFO - 123TV DB import
Fri, 03 Jan 2020 07:28:28 - INFO - Connect to DB
Fri, 03 Jan 2020 07:28:29 - INFO - TRIZMA DB import
Fri, 03 Jan 2020 07:28:29 - INFO - 123TV DB import
Fri, 03 Jan 2020 07:28:38 - INFO - Connect to DB
Fri, 03 Jan 2020 07:28:38 - INFO - TRIZMA DB import
Fri, 03 Jan 2020 07:28:38 - INFO - 123TV DB import
Fri, 03 Jan 2020 07:29:46 - INFO - Connect to DB
Fri, 03 Jan 2020 07:29:46 - INFO - TRIZMA DB import
Fri, 03 Jan 2020 07:29:46 - INFO - 123TV DB import
Fri, 03 Jan 2020 07:30:46 - INFO - Connect to DB
Fri, 03 Jan 2020 07:30:47 - INFO - TRIZMA DB import
Fri, 03 Jan 2020 07:30:47 - INFO - 123TV DB import
Fri, 03 Jan 2020 07:30:52 - INFO - Connect to DB
Fri, 03 Jan 2020 07:30:52 - INFO - TRIZMA DB import
Fri, 03 Jan 2020 07:30:52 - INFO - 123TV DB import
Fri, 03 Jan 2020 07:31:18 - INFO - Connect to DB
Fri, 03 Jan 2020 07:31:18 - INFO - TRIZMA DB import
Fri, 03 Jan 2020 07:31:18 - INFO - 123TV DB import
Fri, 03 Jan 2020 07:31:58 - INFO - Connect to DB
Fri, 03 Jan 2020 07:31:58 - INFO - TRIZMA DB import
Fri, 03 Jan 2020 07:31:58 - INFO - Failed on TRIZMA DB import at: 2020-01-02_18-53-56, for following calling party: 493035525313, for agent id: trz_sstankovic, with error:(pyodbc.DataError) ('22001', '[22001] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]String or binary data would be truncated. (8152) (SQLExecDirectW)')
[SQL: insert into records values('CC2Servicenummer','Belgrad','Nicht übermittelt','trz_sstankovic',                                  '493035525313','','Nicht übermittelt','493035525313_Thursday, January 02, 2020_10:58:43 AM')]
(Background on this error at: http://sqlalche.me/e/9h9h)
Fri, 03 Jan 2020 07:31:58 - INFO - 123TV DB import
Fri, 03 Jan 2020 07:32:19 - INFO - Connect to DB
Fri, 03 Jan 2020 07:32:19 - INFO - TRIZMA DB import
Fri, 03 Jan 2020 07:32:19 - INFO - 123TV DB import
Fri, 03 Jan 2020 07:32:40 - INFO - Connect to DB
Fri, 03 Jan 2020 07:32:40 - INFO - TRIZMA DB import
Fri, 03 Jan 2020 07:32:40 - INFO - 123TV DB import
Fri, 03 Jan 2020 07:33:05 - INFO - Connect to DB
Fri, 03 Jan 2020 07:33:05 - INFO - TRIZMA DB import
Fri, 03 Jan 2020 07:33:05 - INFO - 123TV DB import
Fri, 03 Jan 2020 07:38:55 - INFO - Connect to DB
Fri, 03 Jan 2020 07:38:55 - INFO - TRIZMA DB import
Fri, 03 Jan 2020 07:38:55 - INFO - 123TV DB import
Fri, 03 Jan 2020 07:39:27 - INFO - Connect to DB
Fri, 03 Jan 2020 07:39:27 - INFO - TRIZMA DB import
Fri, 03 Jan 2020 07:39:27 - INFO - 123TV DB import
Fri, 03 Jan 2020 07:39:34 - INFO - Connect to DB
Fri, 03 Jan 2020 07:39:34 - INFO - TRIZMA DB import
Fri, 03 Jan 2020 07:39:35 - INFO - Failed on TRIZMA DB import at: 2020-01-02_18-53-56, for following calling party: 4915738961136, for agent id: trz_bmaksimovic, with error:(pyodbc.DataError) ('22001', '[22001] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]String or binary data would be truncated. (8152) (SQLExecDirectW)')
[SQL: insert into records values('CC2Servicenummer','Belgrad','Nicht übermittelt','trz_bmaksimovic',                                  '4915738961136','','Nicht übermittelt','4915738961136_Tuesday, December 31, 2019_3:07:36 PM')]
(Background on this error at: http://sqlalche.me/e/9h9h)
Fri, 03 Jan 2020 07:39:35 - INFO - 123TV DB import
Fri, 03 Jan 2020 07:39:46 - INFO - Connect to DB
Fri, 03 Jan 2020 07:39:46 - INFO - TRIZMA DB import
Fri, 03 Jan 2020 07:39:46 - INFO - 123TV DB import
Fri, 03 Jan 2020 07:40:26 - INFO - Connect to DB
Fri, 03 Jan 2020 07:40:26 - INFO - TRIZMA DB import
Fri, 03 Jan 2020 07:40:26 - INFO - 123TV DB import
Fri, 03 Jan 2020 07:41:01 - INFO - Connect to DB
Fri, 03 Jan 2020 07:41:01 - INFO - TRIZMA DB import
Fri, 03 Jan 2020 07:41:01 - INFO - Failed on TRIZMA DB import at: 2020-01-02_18-53-56, for following calling party: 4915221020092, for agent id: trz_bmaksimovic, with error:(pyodbc.DataError) ('22001', '[22001] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]String or binary data would be truncated. (8152) (SQLExecDirectW)')
[SQL: insert into records values('CC2Servicenummer','Belgrad','Nicht übermittelt','trz_bmaksimovic',                                  '4915221020092','','Nicht übermittelt','4915221020092_Tuesday, December 31, 2019_6:53:28 PM')]
(Background on this error at: http://sqlalche.me/e/9h9h)
Fri, 03 Jan 2020 07:41:01 - INFO - 123TV DB import
Fri, 03 Jan 2020 07:41:19 - INFO - Connect to DB
Fri, 03 Jan 2020 07:41:19 - INFO - TRIZMA DB import
Fri, 03 Jan 2020 07:41:19 - INFO - 123TV DB import
Fri, 03 Jan 2020 07:41:53 - INFO - Connect to DB
Fri, 03 Jan 2020 07:41:53 - INFO - TRIZMA DB import
Fri, 03 Jan 2020 07:41:53 - INFO - 123TV DB import
Fri, 03 Jan 2020 07:42:35 - INFO - Connect to DB
Fri, 03 Jan 2020 07:42:35 - INFO - TRIZMA DB import
Fri, 03 Jan 2020 07:42:35 - INFO - 123TV DB import
Fri, 03 Jan 2020 07:42:56 - INFO - Connect to DB
Fri, 03 Jan 2020 07:42:56 - INFO - TRIZMA DB import
Fri, 03 Jan 2020 07:42:56 - INFO - Failed on TRIZMA DB import at: 2020-01-02_18-53-56, for following calling party: 4915759164030, for agent id: trz_bmaksimovic, with error:(pyodbc.DataError) ('22001', '[22001] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]String or binary data would be truncated. (8152) (SQLExecDirectW)')
[SQL: insert into records values('CC2Servicenummer','Belgrad','Nicht übermittelt','trz_bmaksimovic',                                  '4915759164030','','Nicht übermittelt','4915759164030_Wednesday, January 1, 2020_7:03:03 PM')]
(Background on this error at: http://sqlalche.me/e/9h9h)
Fri, 03 Jan 2020 07:42:56 - INFO - 123TV DB import
Fri, 03 Jan 2020 07:44:12 - INFO - Connect to DB
Fri, 03 Jan 2020 07:44:12 - INFO - TRIZMA DB import
Fri, 03 Jan 2020 07:44:12 - INFO - 123TV DB import
Fri, 03 Jan 2020 07:45:29 - INFO - Connect to DB
Fri, 03 Jan 2020 07:45:29 - INFO - TRIZMA DB import
Fri, 03 Jan 2020 07:45:29 - INFO - 123TV DB import
