Mon, 06 Jan 2020 07:40:56 - INFO - Connect to DB
Mon, 06 Jan 2020 07:40:56 - INFO - TRIZMA DB import
Mon, 06 Jan 2020 07:40:56 - INFO - 123TV DB import
Mon, 06 Jan 2020 07:46:02 - INFO - Connect to DB
Mon, 06 Jan 2020 07:46:02 - INFO - TRIZMA DB import
Mon, 06 Jan 2020 07:46:02 - INFO - 123TV DB import
Mon, 06 Jan 2020 07:47:22 - INFO - Connect to DB
Mon, 06 Jan 2020 07:47:22 - INFO - TRIZMA DB import
Mon, 06 Jan 2020 07:47:22 - INFO - 123TV DB import
Mon, 06 Jan 2020 07:51:21 - INFO - Connect to DB
Mon, 06 Jan 2020 07:51:21 - INFO - TRIZMA DB import
Mon, 06 Jan 2020 07:51:22 - INFO - 123TV DB import
Mon, 06 Jan 2020 07:55:29 - INFO - Connect to DB
Mon, 06 Jan 2020 07:55:29 - INFO - TRIZMA DB import
Mon, 06 Jan 2020 07:55:29 - INFO - Failed on TRIZMA DB import at: 2020-01-06_07-35-28, for following calling party: 493035525313, for agent id: trz_sstankovic, with error:(pyodbc.DataError) ('22001', '[22001] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]String or binary data would be truncated. (8152) (SQLExecDirectW)')
[SQL: insert into records values('CC2Servicenummer','Belgrad','Nicht 端bermittelt','trz_sstankovic',                                  '493035525313','','Nicht 端bermittelt','493035525313_Thursday, January 02, 2020_10:58:43 AM')]
(Background on this error at: http://sqlalche.me/e/9h9h)
Mon, 06 Jan 2020 07:55:29 - INFO - 123TV DB import
Mon, 06 Jan 2020 07:56:00 - INFO - Connect to DB
Mon, 06 Jan 2020 07:56:00 - INFO - TRIZMA DB import
Mon, 06 Jan 2020 07:56:00 - INFO - 123TV DB import
Mon, 06 Jan 2020 07:56:35 - INFO - Connect to DB
Mon, 06 Jan 2020 07:56:35 - INFO - TRIZMA DB import
Mon, 06 Jan 2020 07:56:35 - INFO - 123TV DB import
Mon, 06 Jan 2020 07:58:21 - INFO - Connect to DB
Mon, 06 Jan 2020 07:58:21 - INFO - TRIZMA DB import
Mon, 06 Jan 2020 07:58:21 - INFO - 123TV DB import
Mon, 06 Jan 2020 08:02:54 - INFO - Connect to DB
Mon, 06 Jan 2020 08:02:54 - INFO - TRIZMA DB import
Mon, 06 Jan 2020 08:02:54 - INFO - 123TV DB import
Mon, 06 Jan 2020 08:03:00 - INFO - Connect to DB
Mon, 06 Jan 2020 08:03:00 - INFO - TRIZMA DB import
Mon, 06 Jan 2020 08:03:00 - INFO - 123TV DB import
Mon, 06 Jan 2020 08:04:33 - INFO - Connect to DB
Mon, 06 Jan 2020 08:04:33 - INFO - TRIZMA DB import
Mon, 06 Jan 2020 08:04:34 - INFO - 123TV DB import
Mon, 06 Jan 2020 08:09:05 - INFO - Connect to DB
Mon, 06 Jan 2020 08:09:05 - INFO - TRIZMA DB import
Mon, 06 Jan 2020 08:09:05 - INFO - 123TV DB import
Mon, 06 Jan 2020 08:13:02 - INFO - Connect to DB
Mon, 06 Jan 2020 08:13:02 - INFO - TRIZMA DB import
Mon, 06 Jan 2020 08:13:02 - INFO - 123TV DB import
Mon, 06 Jan 2020 08:13:55 - INFO - Connect to DB
Mon, 06 Jan 2020 08:13:55 - INFO - TRIZMA DB import
Mon, 06 Jan 2020 08:13:55 - INFO - 123TV DB import
Mon, 06 Jan 2020 08:15:34 - INFO - Connect to DB
Mon, 06 Jan 2020 08:15:34 - INFO - TRIZMA DB import
Mon, 06 Jan 2020 08:15:34 - INFO - 123TV DB import
Mon, 06 Jan 2020 08:19:29 - INFO - Connect to DB
Mon, 06 Jan 2020 08:19:29 - INFO - TRIZMA DB import
Mon, 06 Jan 2020 08:19:29 - INFO - 123TV DB import
Mon, 06 Jan 2020 08:20:24 - INFO - Connect to DB
Mon, 06 Jan 2020 08:20:24 - INFO - TRIZMA DB import
Mon, 06 Jan 2020 08:20:24 - INFO - Failed on TRIZMA DB import at: 2020-01-06_07-35-28, for following calling party: 4917696942581, for agent id: trz_sstankovic, with error:(pyodbc.DataError) ('22001', '[22001] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]String or binary data would be truncated. (8152) (SQLExecDirectW)')
[SQL: insert into records values('CC2Servicenummer','Belgrad','Nicht 端bermittelt','trz_sstankovic',                                  '4917696942581','','Nicht 端bermittelt','4917696942581_Saturday, January 04, 2020_8:06:07 AM')]
(Background on this error at: http://sqlalche.me/e/9h9h)
Mon, 06 Jan 2020 08:20:24 - INFO - 123TV DB import
