Fri, 10 Jan 2020 13:20:42 - INFO - Connect to DB
Fri, 10 Jan 2020 13:20:42 - INFO - TRIZMA DB import
Fri, 10 Jan 2020 13:20:42 - INFO - 123TV DB import
Fri, 10 Jan 2020 13:28:53 - INFO - Connect to DB
Fri, 10 Jan 2020 13:28:53 - INFO - TRIZMA DB import
Fri, 10 Jan 2020 13:28:53 - INFO - 123TV DB import
Fri, 10 Jan 2020 13:32:16 - INFO - Connect to DB
Fri, 10 Jan 2020 13:32:16 - INFO - TRIZMA DB import
Fri, 10 Jan 2020 13:32:16 - INFO - 123TV DB import
Fri, 10 Jan 2020 13:33:28 - INFO - Connect to DB
Fri, 10 Jan 2020 13:33:28 - INFO - TRIZMA DB import
Fri, 10 Jan 2020 13:33:28 - INFO - 123TV DB import
Fri, 10 Jan 2020 13:38:32 - INFO - Connect to DB
Fri, 10 Jan 2020 13:38:32 - INFO - TRIZMA DB import
Fri, 10 Jan 2020 13:38:32 - INFO - 123TV DB import
Fri, 10 Jan 2020 13:38:57 - INFO - Connect to DB
Fri, 10 Jan 2020 13:38:57 - INFO - TRIZMA DB import
Fri, 10 Jan 2020 13:38:57 - INFO - 123TV DB import
Fri, 10 Jan 2020 13:39:42 - INFO - Connect to DB
Fri, 10 Jan 2020 13:39:42 - INFO - TRIZMA DB import
Fri, 10 Jan 2020 13:39:43 - INFO - Failed on TRIZMA DB import at: 2020-01-10_13-18-53, for following calling party: 4917657736965, for agent id: trz_bmaksimovic, with error:(pyodbc.DataError) ('22001', '[22001] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]String or binary data would be truncated. (8152) (SQLExecDirectW)')
[SQL: insert into records values('CC2Servicenummer','Belgrad','Nicht übermittelt','trz_bmaksimovic',                                  '4917657736965','','Nicht übermittelt','4917657736965_Wednesday, January 8, 2020_6:44:51 PM')]
(Background on this error at: http://sqlalche.me/e/9h9h)
Fri, 10 Jan 2020 13:39:43 - INFO - 123TV DB import
Fri, 10 Jan 2020 13:40:18 - INFO - Connect to DB
Fri, 10 Jan 2020 13:40:18 - INFO - TRIZMA DB import
Fri, 10 Jan 2020 13:40:18 - INFO - 123TV DB import
