Fri, 10 Jan 2020 12:34:48 - INFO - Connect to DB
Fri, 10 Jan 2020 12:34:48 - INFO - TRIZMA DB import
Fri, 10 Jan 2020 12:34:48 - INFO - 123TV DB import
Fri, 10 Jan 2020 12:36:57 - INFO - Connect to DB
Fri, 10 Jan 2020 12:36:57 - INFO - TRIZMA DB import
Fri, 10 Jan 2020 12:36:57 - INFO - 123TV DB import
Fri, 10 Jan 2020 12:38:27 - INFO - Connect to DB
Fri, 10 Jan 2020 12:38:27 - INFO - TRIZMA DB import
Fri, 10 Jan 2020 12:38:27 - INFO - 123TV DB import
Fri, 10 Jan 2020 12:44:13 - INFO - Connect to DB
Fri, 10 Jan 2020 12:44:13 - INFO - TRIZMA DB import
Fri, 10 Jan 2020 12:44:13 - INFO - 123TV DB import
Fri, 10 Jan 2020 12:44:23 - INFO - Connect to DB
Fri, 10 Jan 2020 12:44:23 - INFO - TRIZMA DB import
Fri, 10 Jan 2020 12:44:23 - INFO - 123TV DB import
Fri, 10 Jan 2020 12:49:03 - INFO - Connect to DB
Fri, 10 Jan 2020 12:49:03 - INFO - TRIZMA DB import
Fri, 10 Jan 2020 12:49:03 - INFO - Failed on TRIZMA DB import at: 2020-01-10_12-33-41, for following calling party: 492191667776, for agent id: trz_madamovic, with error:(pyodbc.DataError) ('22001', '[22001] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]String or binary data would be truncated. (8152) (SQLExecDirectW)')
[SQL: insert into records values('CC2Servicenummer','Belgrad','Nicht übermittelt','trz_madamovic',                                  '492191667776','','Nicht übermittelt','492191667776_Thursday, January 09, 2020_12:47:14 PM')]
(Background on this error at: http://sqlalche.me/e/9h9h)
Fri, 10 Jan 2020 12:49:03 - INFO - 123TV DB import
Fri, 10 Jan 2020 12:49:43 - INFO - Connect to DB
Fri, 10 Jan 2020 12:49:43 - INFO - TRIZMA DB import
Fri, 10 Jan 2020 12:49:44 - INFO - 123TV DB import
