Wed, 22 Jan 2020 10:57:35 - INFO - Connect to DB
Wed, 22 Jan 2020 10:57:36 - INFO - TRIZMA DB import
Wed, 22 Jan 2020 10:57:36 - INFO - 123TV DB import
Wed, 22 Jan 2020 11:04:47 - INFO - Connect to DB
Wed, 22 Jan 2020 11:04:47 - INFO - TRIZMA DB import
Wed, 22 Jan 2020 11:04:47 - INFO - 123TV DB import
Wed, 22 Jan 2020 11:12:01 - INFO - Connect to DB
Wed, 22 Jan 2020 11:12:01 - INFO - TRIZMA DB import
Wed, 22 Jan 2020 11:12:01 - INFO - 123TV DB import
Wed, 22 Jan 2020 11:12:07 - INFO - Connect to DB
Wed, 22 Jan 2020 11:12:07 - INFO - TRIZMA DB import
Wed, 22 Jan 2020 11:12:07 - INFO - 123TV DB import
Wed, 22 Jan 2020 11:12:26 - INFO - Connect to DB
Wed, 22 Jan 2020 11:12:26 - INFO - TRIZMA DB import
Wed, 22 Jan 2020 11:12:26 - INFO - 123TV DB import
Wed, 22 Jan 2020 11:13:15 - INFO - Connect to DB
Wed, 22 Jan 2020 11:13:15 - INFO - TRIZMA DB import
Wed, 22 Jan 2020 11:13:15 - INFO - 123TV DB import
Wed, 22 Jan 2020 11:15:56 - INFO - Connect to DB
Wed, 22 Jan 2020 11:15:56 - INFO - TRIZMA DB import
Wed, 22 Jan 2020 11:15:56 - INFO - Failed on TRIZMA DB import at: 2020-01-22_10-57-04, for following calling party: 491734367913, for agent id: trz_memetovic, with error:(pyodbc.DataError) ('22001', '[22001] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]String or binary data would be truncated. (8152) (SQLExecDirectW)')
[SQL: insert into records values('CC2Servicenummer','Belgrad','Nicht übermittelt','trz_memetovic',                                 '491734367913','','Nicht übermittelt','491734367913_Wednesday, January 22, 2020_12:15:50 PM','KEN_MEMETO')]
(Background on this error at: http://sqlalche.me/e/9h9h)
Wed, 22 Jan 2020 11:15:56 - INFO - 123TV DB import
