Fri, 10 Jan 2020 11:50:30 - INFO - Connect to DB
Fri, 10 Jan 2020 11:50:30 - INFO - TRIZMA DB import
Fri, 10 Jan 2020 11:50:30 - INFO - 123TV DB import
Fri, 10 Jan 2020 11:50:35 - INFO - Connect to DB
Fri, 10 Jan 2020 11:50:35 - INFO - TRIZMA DB import
Fri, 10 Jan 2020 11:50:35 - INFO - 123TV DB import
Fri, 10 Jan 2020 11:51:05 - INFO - Connect to DB
Fri, 10 Jan 2020 11:51:05 - INFO - TRIZMA DB import
Fri, 10 Jan 2020 11:51:05 - INFO - 123TV DB import
Fri, 10 Jan 2020 11:56:50 - INFO - Connect to DB
Fri, 10 Jan 2020 11:56:50 - INFO - TRIZMA DB import
Fri, 10 Jan 2020 11:56:50 - INFO - 123TV DB import
Fri, 10 Jan 2020 11:57:59 - INFO - Connect to DB
Fri, 10 Jan 2020 11:57:59 - INFO - TRIZMA DB import
Fri, 10 Jan 2020 11:57:59 - INFO - 123TV DB import
Fri, 10 Jan 2020 12:03:30 - INFO - Connect to DB
Fri, 10 Jan 2020 12:03:30 - INFO - TRIZMA DB import
Fri, 10 Jan 2020 12:03:30 - INFO - 123TV DB import
Fri, 10 Jan 2020 12:04:48 - INFO - Connect to DB
Fri, 10 Jan 2020 12:04:48 - INFO - TRIZMA DB import
Fri, 10 Jan 2020 12:04:48 - INFO - Failed on TRIZMA DB import at: 2020-01-10_11-49-55, for following calling party: 49307066241, for agent id: trz_madamovic, with error:(pyodbc.DataError) ('22001', '[22001] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]String or binary data would be truncated. (8152) (SQLExecDirectW)')
[SQL: insert into records values('CC2Servicenummer','Belgrad','Nicht übermittelt','trz_madamovic',                                  '49307066241','','Nicht übermittelt','49307066241_Wednesday, January 08, 2020_11:15:38 AM')]
(Background on this error at: http://sqlalche.me/e/9h9h)
Fri, 10 Jan 2020 12:04:48 - INFO - 123TV DB import
