Sun, 29 Dec 2019 08:48:38 - INFO - Connect to DB
Sun, 29 Dec 2019 08:48:38 - INFO - TRIZMA DB import
Sun, 29 Dec 2019 08:48:39 - INFO - 123TV DB import
Sun, 29 Dec 2019 08:49:00 - INFO - Connect to DB
Sun, 29 Dec 2019 08:49:00 - INFO - TRIZMA DB import
Sun, 29 Dec 2019 08:49:00 - INFO - 123TV DB import
Sun, 29 Dec 2019 08:49:28 - INFO - Connect to DB
Sun, 29 Dec 2019 08:49:28 - INFO - TRIZMA DB import
Sun, 29 Dec 2019 08:49:28 - INFO - 123TV DB import
Sun, 29 Dec 2019 09:00:30 - INFO - Connect to DB
Sun, 29 Dec 2019 09:00:30 - INFO - TRIZMA DB import
Sun, 29 Dec 2019 09:00:30 - INFO - 123TV DB import
Sun, 29 Dec 2019 09:01:26 - INFO - Connect to DB
Sun, 29 Dec 2019 09:01:26 - INFO - TRIZMA DB import
Sun, 29 Dec 2019 09:01:26 - INFO - 123TV DB import
Sun, 29 Dec 2019 09:02:27 - INFO - Connect to DB
Sun, 29 Dec 2019 09:02:27 - INFO - TRIZMA DB import
Sun, 29 Dec 2019 09:02:27 - INFO - 123TV DB import
Sun, 29 Dec 2019 09:13:23 - INFO - Connect to DB
Sun, 29 Dec 2019 09:13:23 - INFO - TRIZMA DB import
Sun, 29 Dec 2019 09:13:23 - INFO - 123TV DB import
Sun, 29 Dec 2019 09:18:54 - INFO - Connect to DB
Sun, 29 Dec 2019 09:18:54 - INFO - TRIZMA DB import
Sun, 29 Dec 2019 09:18:54 - INFO - 123TV DB import
Sun, 29 Dec 2019 09:21:30 - INFO - Connect to DB
Sun, 29 Dec 2019 09:21:30 - INFO - TRIZMA DB import
Sun, 29 Dec 2019 09:21:30 - INFO - Failed on TRIZMA DB import at: 2019-12-29_08-48-38, for following calling party: 491739921985, for agent id: trz_sstankovic, with error:(pyodbc.DataError) ('22001', '[22001] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]String or binary data would be truncated. (8152) (SQLExecDirectW)')
[SQL: insert into records values('CC2Servicenummer','Belgrad','Nicht übermittelt','trz_sstankovic',                                  '491739921985','','Nicht übermittelt','491739921985_Saturday, December 28, 2019_10:35:04 AM')]
(Background on this error at: http://sqlalche.me/e/9h9h)
Sun, 29 Dec 2019 09:21:30 - INFO - 123TV DB import
